# This is just a template placeholder docker-compose file. Use relevant sections which are applicable,
# and feel free to customize.
version: '3.8'

services:
  frontend:
    # Specify the build context for the frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # Map the host port to the container port
    ports:
      - '3000:3000'
    # Specify dependencies (if applicable)
    depends_on:
      - backend

    # Additional options (uncomment and configure as needed):

    # Specify environment variables if needed
    environment:
      - REACT_APP_API_URL=http://backend:5000
      - NODE_ENV=production
      - PORT=3000

    # Specify volume for live code reloading (optional)
    volumes:
      - ./frontend:/app
      - /app/node_modules

    # Specify the command to run the development server (if different from Dockerfile)
    # command:

  backend:
    # Specify the build context for the backend
    build:
      context: ./backend
      dockerfile: Dockerfile

    # Map the host port to the container port
    ports:
      - '5000:5000'

    # Additional options (uncomment and configure as needed):

    # Specify environment variables if needed
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_RUN_HOST=0.0.0.0
      - PORT=5000

    # Specify volume for live code reloading (optional)
    volumes:
      - ./backend:/app
      - /app/node_modules

    # Specify the command to run the development server (if different from Dockerfile)
    command: ['gunicorn', '-b', '0.0.0.0:5000', 'app:app']
# Additional components (uncomment and configure as needed):
# Define a custom network (if applicable)
# networks:
#   - my-network

# Define volumes (if applicable)
# volumes:
